services:
  pi:
    build:
      context: .
      dockerfile: Dockerfile.pi
    volumes:
      - ~/.pi/skills:/root/.pi/agent/skills
      - ./auth.json:/root/.pi/agent/auth.json
      - ./:/workspace
    ports:
      - 8002:8000
